-- Drop the old table if it exists
DROP TABLE IF EXISTS public.us_market;

-- Create the table with correct types
CREATE TABLE public.us_market (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT,
    description TEXT,
    enterprise_value DOUBLE PRECISION,
    enterprise_value_currency TEXT,
    market_capitalization DOUBLE PRECISION,
    market_capitalization_currency TEXT,
    total_debt_quarterly DOUBLE PRECISION,
    total_debt_quarterly_currency TEXT,
    total_equity_quarterly DOUBLE PRECISION,
    total_equity_quarterly_currency TEXT,
    total_assets_quarterly DOUBLE PRECISION,
    total_assets_quarterly_currency TEXT,
    beta_5_years DOUBLE PRECISION,
    cash_from_operating_activities_trailing_12_months DOUBLE PRECISION,
    cash_from_operating_activities_trailing_12_months_currency TEXT,
    cash_from_financing_activities_trailing_12_months DOUBLE PRECISION,
    cash_from_financing_activities_trailing_12_months_currency TEXT,
    total_cash_dividends_paid_annual DOUBLE PRECISION,
    total_cash_dividends_paid_annual_currency TEXT,
    industry TEXT,
    sector TEXT,
    exchange TEXT,
    "index" TEXT,
    beta_5_years_1 DOUBLE PRECISION,
    beta_1_year DOUBLE PRECISION,
    simple_moving_average_120_1_day DOUBLE PRECISION,
    exponential_moving_average_120_1_day DOUBLE PRECISION,
    return_on_invested_capital_percent_trailing_12_months DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.us_market ENABLE ROW LEVEL SECURITY;

-- Add policies for public read and service role write
CREATE POLICY "Allow public read" ON public.us_market FOR SELECT USING (true);
CREATE POLICY "Allow service insert" ON public.us_market FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service update" ON public.us_market FOR UPDATE WITH CHECK (true);
CREATE POLICY "Allow service delete" ON public.us_market FOR DELETE USING (true);
